### ISSUE TITLE
IdentityAgent: connection from IdentityAgent to a configured RootUpdater

### ISSUE THREAD

**Issue by arnaucube** [iden3/go-iden3-core#167]
When creating the IdentityAgentService allow to specify the configuration of the RootUpdater. In the initial version RootUpdater can be a Relay.
Each action of the IdentityAgentService that modifies the MerkleTree will use RootUpdater to commit the Identity Root to the blockchain (directly or using a Relay)

**Comment by ed255** [comment]
The RootUpdater needs the following functions:
- UpdateRoot (updates the root in the blockchain directly or indirectly via a relay)
- Obtain a proof of the root.
  - if the update is direct, the proof is nil because it can be publicly checked in the blockchain
  - if the update is indirect, the proof shows that a relay root that is in the blockchain has a valid leaf with a SetRoot with the identity root.  It's also required to prove that the identity is authorizing that relay.
  - * In both cases, the root that is in the blockchain needs to be returned with the timestamp and block number.

UpdateRoot has a special case when the identity is not yet in the blockchain.

**Comment by arnaucube** [comment]
Deprecated
