### ISSUE TITLE
Genesis claims can't be upgraded

### ISSUE THREAD

**Issue by ed255** [iden3/go-iden3-core#184]
To simplify our design, my proposal is that claims that are in the genesis tree are valid for that identity forever: they can't be updated (with new versions), and they can't be revoked.
Updating and revoking would be achieved with an upgrade process of the identity that needs to be defined.  This allows us to have a special kind of claim proofs: genesis claim proofs, that can be verified without relaying on an external source of truth.

This is very useful for identities that never publish their roots to the blockchain directly, but do so through a relay, because it allows the identity to prove claims to the relay (otherwise we get in a loop), and allows the identity to prove claims to others despite the relay (like the claim that authorizes such relay).

**Comment by arnaucube** [comment]
Agree, in order to recap, this morning we've agreed on:
- minor updates doesn't allow to change the authorized Relay for an identity (neither revoke)
- major updates allow to change the Relay, but require a special procedure

So, the Relay is set in the Genesis Claims, and can not be revoked until a Major update of the identity state
