### ISSUE TITLE
IdenPubHTTP.Publish() when calling merkletree.DumpTreeIoWritter crop leafs that have empty elements (such as LeafRoT)

### ISSUE THREAD

**Issue by arnaucube** [iden3/go-iden3-core#288]
In order to save space

**Comment by ed255** [comment]
Currently the Tree is serialized in JSON, where each node is hex encoded in an array, and the leave nodes are a full claim.

Ideally there should be the following changes:
- The leaves shouldn't be the full claim, since using a claim is a hack.  The leaves should be just the root for the RoT, and the (nonce, version) for the Ret.
- Using hex encoding is rather space consuming, since each byte becomes two bytes.  A first step would be to use base64.
- For best space efficiency, the tree should be encoded in binary.
- Maybe the MerkleTree should be reworked to allow arbitrary size leafs, instead of the fixed size 8 elements claims we have now.
